# Introductory assignment on ethics with an introduction to NumPy and Pandas

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python, NumPy, and Pandas

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy and Pandas, Jupyter Notebooks, etc that we will rely upon routinely.

## Exercises 1-5
For the following exercises you can find assistance from the Python appendix PDF provided on Canvas written by Marsland OR **you may find help online via Google or ChatGPT.** Don't turn on the code completion feature in Colab as they will take away too much of the opportunity to learn.

In [3]:
import numpy as np

#### Exercise 1. Make an array a of size 6 × 4 where every element is a 2.

In [7]:
def exercise_1():
    a = None
    a = np.full((6,4), 2)
    return a

a = exercise_1()
a

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

#### Exercise 2. Make an array b of size 6 × 4 that has 3 on the leading diagonal and 1 everywhere else. (You can do this without loops.)

In [34]:
def exercise_2():
    b = None
    b = np.ones((6,4), dtype=np.int64)
    b[0,0] =3
    return b

b = exercise_2()
b

array([[3, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### Stop and think: Why can you multiply these two matrices together? Why does a * b work, but not dot(a,b)?

In [ ]:
a*b

array([[6., 2., 2., 2.],
       [2., 6., 2., 2.],
       [2., 2., 6., 2.],
       [2., 2., 2., 6.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [ ]:
import numpy as np

np.dot(a,b)

ValueError: shapes (6,4) and (6,4) not aligned: 4 (dim 1) != 6 (dim 0)

You can multiple two matrices together because they have the same dimesions which is needed for multiplying matrices. For dot product, you need a matrix that has the opposite dmensions. For example for this dot product to work, b would need to have a dimension of [4,6] instead of [6,4].



> Add blockquote

#### Stop and Think: Compute dot(a.transpose(),b) and dot(a,b.transpose()). Why are the results different shapes?

In [14]:
np.dot(a.transpose(),b)

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

In [15]:
np.dot(a,b.transpose())

array([[12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8]])

When you transpose a matrix, you are flipping over the diagonal and swithcing the rows and columns so the [i,j] matrix turns into a [j, i] matrix. Since you are transposing different matrices the shapes will be different because the number of the rows in the first matrix must be the same as the number of columns. So for the first example after the transposition of a, it is [4, 6] and [6,4] so the matrix shape fo their dot product will be 4x4. For the second example after the transposition of b, it is [6,4] and [4,6] so the matrix shape is 6x6.

#### Exercise 3. Find the overall mean of matrix ``c``.

In [18]:
np.random.seed(1)
c = np.random.rand(6,4)
display(c)

def exercise_3(c):
    m = None
    c.mean()
    return m

m = exercise_3(c)
m

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01],
       [3.96767474e-01, 5.38816734e-01, 4.19194514e-01, 6.85219500e-01],
       [2.04452250e-01, 8.78117436e-01, 2.73875932e-02, 6.70467510e-01],
       [4.17304802e-01, 5.58689828e-01, 1.40386939e-01, 1.98101489e-01],
       [8.00744569e-01, 9.68261576e-01, 3.13424178e-01, 6.92322616e-01]])

#### Exercise 4. Find the column and row means of matrix ``c``.

In [20]:
def exercise_4(c):
    row_means,col_means = None,None
    row_means = c.mean(axis=1)
    col_means = c.mean(axis=0)
    return row_means,col_means

row_means,col_means = exercise_4(c)
display(row_means)
display(col_means)

array([0.35994836, 0.19272886, 0.50999956, 0.4451062 , 0.32862076,
       0.69368823])

array([0.3971745 , 0.62609144, 0.18112797, 0.48233407])

#### Exercise 5. Write a function that consists of a set of loops that run through an array and counts the number of ones in it. Do the same thing without using a for loop. For inspiration, check out the following. You don't need to use all of them, but pick one.

In [21]:
b == 1

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [22]:
np.where(b == 1)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5]),
 array([1, 2, 3, 0, 2, 3, 0, 1, 3, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3]))

In [23]:
np.array(b.flat)

array([3, 1, 1, 1, 1, 3, 1, 1, 1, 1, 3, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1,
       1, 1])

In [24]:
np.where(b.flat == 1)

(array([ 1,  2,  3,  4,  6,  7,  8,  9, 11, 12, 13, 14, 16, 17, 18, 19, 20,
        21, 22, 23]),)

In [28]:
def exercise_5(a):
    c1 = 0
    c2 = 0
    for i in range(a.shape[0]):
      for j in range(a.shape[1]):
        if a[i,j] == 1:
          c1 += 1
    c2 = np.count_nonzero(a == 1)
    return c1,c2

c1,c2 = exercise_5(b)

c1,c2

(20, 20)

## Excercises 6-7
We will use Pandas at times throughout this course. If needed, please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html).

In [30]:
import pandas as pd

#### Exercise 6. Repeat Exercise 1, but create a Pandas DataFrame instead of a NumPy array.

In [31]:
def exercise_6():
    a = None
    a = pd.DataFrame(np.full((6,4), 2))
    return a

a = exercise_6()
a

   0  1  2  3
0  2  2  2  2
1  2  2  2  2
2  2  2  2  2
3  2  2  2  2
4  2  2  2  2
5  2  2  2  2

#### Exercise 7. Repeat exercise 2 using a DataFrame instead.

In [35]:
def exercise_7():
    b = None
    b = pd.DataFrame(np.ones((6,4), dtype=np.int64))
    b.iloc[0,0] = 3
    return b

b = exercise_7()
b

   0  1  2  3
0  3  1  1  1
1  1  1  1  1
2  1  1  1  1
3  1  1  1  1
4  1  1  1  1
5  1  1  1  1

#### Stop and think: What if we want to go from a pandas dataframe to a numpy array?

## Exercises 8-10
Now let's look at a real dataset, and talk about ``.iloc`` and ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [36]:
import pandas as pd
titanic_df = pd.read_csv(
    f"https://raw.githubusercontent.com/Anderson-Lab/csc-466-student/refs/heads/main/data/titanic.csv"
)
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [37]:
titanic_df.index # default index

RangeIndex(start=0, stop=891, step=1)

#### Stop and think: How would you set the index of the data frame to the Sex column and then select only those passengers who are female?

In [ ]:
df = titanic_df.set_index('Sex').loc['female']
df

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Sex,,,,,,,,,,,
female,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,C
female,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
female,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S
female,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",27.0,0,2,347742,11.1333,NaN,S
female,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...
female,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",25.0,0,1,230433,26.0000,NaN,S
female,883,0,3,"Dahlberg, Miss. Gerda Ulrika",22.0,0,0,7552,10.5167,NaN,S
female,886,0,3,"Rice, Mrs. William (Margaret Norton)",39.0,0,5,382652,29.1250,NaN,Q
female,888,1,1,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,B42,S
female,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,1,2,W./C. 6607,23.4500,NaN,S

What is important about the above statement is we have used ``.loc`` when we want to reference the pandas dataframe index. This index can be integers (starting at 0 or 1 or random). Further, it could just be a string like the example above. If you want a traditional index like you would in an array, then use ``iloc``.

#### Stop and think: Without setting or using the index, return a new dataframe with only those passengers who survived

In [ ]:
inxs = np.where(titanic_df.Survived==1)
titanic_df.iloc[inxs]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

#### Exercise 8. Select the ``Name`` column without using .iloc?

In [38]:
def exercise_8(df):
    sel = None
    sel = df['Name']
    return sel

sel = exercise_8(titanic_df)
sel

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

#### Exercise 9. After setting the index to ``Sex``, select all passengers that are ``Male``?

In [39]:
def exercise_9(df):
    sel = None
    sel = df.set_index('Sex').loc['male']
    return sel

sel = exercise_9(titanic_df)
sel

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Sex,,,,,,,,,,,
male,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,S
male,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,S
male,6,0,3,"Moran, Mr. James",NaN,0,0,330877,8.4583,NaN,Q
male,7,0,1,"McCarthy, Mr. Timothy J",54.0,0,0,17463,51.8625,E46,S
male,8,0,3,"Palsson, Master. Gosta Leonard",2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
male,884,0,2,"Banfield, Mr. Frederick James",28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
male,885,0,3,"Sutehall, Mr. Henry Jr",25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
male,887,0,2,"Montvila, Rev. Juozas",27.0,0,0,211536,13.0000,NaN,S
male,890,1,1,"Behr, Mr. Karl Howell",26.0,0,0,111369,30.0000,C148,C
male,891,0,3,"Dooley, Mr. Patrick",32.0,0,0,370376,7.7500,NaN,Q

#### Exercise 10. Reset the index of ``titanic_df_copy``.

In [41]:
titanic_df_copy = titanic_df.set_index('Name')
def exercise_10(df):
    df.reset_index(inplace = True)
    return

exercise_10(titanic_df_copy)
titanic_df_copy

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C
890,"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

# Ethics

We are finally ready to think about KDD ethics!

We have preprocessed a dataset on loan applications to make this example appropriate for linear regression. The independent variable data is real and has not been modified apart from being transformed (e.g., Married=Yes => Married=1.). In other words, this is a real dataset with minimal modifcations.

Our client is a loan company, they would like you to look at this historical data of 296 loans which have been approved for varying amounts and stored in the column LoanAmountApproved. They are interested in extracting which independent variables are the most influential/important when predicting the amount of the approved loan. Upon ethical review, they have determined that ``Gender`` is a protected column and should not be considered in the analysis.

In [43]:
import pandas as pd

# Read in the data into a pandas dataframe
credit = pd.read_csv(f"https://raw.githubusercontent.com/Anderson-Lab/csc-466-student/refs/heads/main/data/credit.csv",index_col=0)
credit.head()

,Married,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,Loan_Amount_Term,Credit_History,Property_Area,Gender,LoanAmountApproved
1,1.0,1,0.0,4583,1508.0,360.0,1.0,0.0,0.0,366797.0
2,1.0,1,1.0,3000,0.0,360.0,1.0,1.0,0.0,242073.0
3,1.0,0,0.0,2583,2358.0,360.0,1.0,1.0,0.0,162284.0
4,0.0,1,0.0,6000,0.0,360.0,1.0,1.0,0.0,356509.0
5,1.0,1,1.0,5417,4196.0,360.0,1.0,1.0,0.0,371674.0

#### Exercise 11. Construct a linear model model.

Your model should predict LoanAmountApproved using all of the columns except ``Gender`` which after an ethical and legal review was deemed inappropriate and illegal to consider when making a determination on the amount of loan approved for an applicant.

Use ``sklearn.linear_model.LinearRegression`` with the default constructor arguments. You'll need to call ``.fit``. The documentation for this is so easy to get I almost hesitate to put a link in here, but here you go :)

https://scikit-learn.org/stable/modules/linear_model.html#ordinary-least-squares

In [48]:
from sklearn.linear_model import LinearRegression


X = credit.drop(['Gender','LoanAmountApproved'],axis=1)
y = credit['LoanAmountApproved']

def exercise_11(X,y):
    model = LinearRegression()
    model.fit(X,y)
    return model

model = exercise_11(X,y)

# Here is code that takes the numpy array of coefficients stored in model.coef_ and formats it nicely for the screen
coef = pd.Series(model.coef_,index=X.columns)
coef.abs().sort_values(ascending=False) # this takes the absolute value and then sorts the values in descending order

Married              70486.456486
Education            16443.486789
Self_Employed         8051.192483
Property_Area         3148.984202
Credit_History        1968.229524
ApplicantIncome         49.547937
Loan_Amount_Term        47.370787
CoapplicantIncome        0.539701
dtype: float64

Now let's write some code that calculates the mean absolute error of our model which is one measure of how good our model is performing. Looks like we are approximately $27K off in our model on average.

In [54]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y,model.predict(X))

26916.85266008547

The company asks you for your interpretation of the model. You say that being married is a high indicator of receiving a high amount for a loan. This surprises some of your colleagues, but they think this is reasonable to them. Everyone seems happy with the work. However, an experienced data scientist on your team suggests you run a correlation of the columns used in the regression against the column ``Gender`` since it is considered a protected column. You do so quickly to satisfy this request and get:

In [53]:
Xgender = X.copy()
Xgender['Gender'] = credit['Gender']
Xgender.corr().loc['Gender'].abs().sort_values(ascending=False).drop('Gender')

Married              0.361358
CoapplicantIncome    0.164699
Loan_Amount_Term     0.148585
Education            0.081054
Self_Employed        0.033836
ApplicantIncome      0.024081
Property_Area        0.018244
Credit_History       0.007251
Name: Gender, dtype: float64

#### Problem 1:

What do you think about the results? Specifically, is the fact that Married is correlated with Gender at a correlation of 0.36 concerning from an ethical standpoint? What do you as an individual think? Can you think of any suggestions about what to do? What ethical framework did you use in your decision making process: Utilitarianism, Deontology, or Virtue-ethics.

Let's assume your suggestion was to remove it. Do so and then compare the accuracy of the model

In [55]:
from sklearn.linear_model import LinearRegression
X2 = credit.drop(['Gender','LoanAmountApproved', "Married"],axis=1)
y = credit['LoanAmountApproved']

def exercise_11(X,y):
    model = LinearRegression()
    model.fit(X,y)
    return model

model2 = exercise_11(X2,y)

# Here is code that takes the numpy array of coefficients stored in model.coef_ and formats it nicely for the screen
coef = pd.Series(model.coef_,index=X.columns)
coef.abs().sort_values(ascending=False) # this takes the absolute value and then sorts the values in descending order
# YOUR SOLUTION HERE
# X2 = # make this a dataframe without the married column
# model2 = # make this your linear model
mean_absolute_error(y,model2.predict(X2))

39450.6338289213

#### Problem 2:

What do you think now, should you drop it? Your prediction is now off by more than $10,000. Is this ok?

I would say that since the Married column is not a protected column itself and that even though there is a correlation it shouldn't be dropped. The correlation rate isn't even that high and correlation isn't causation so I would keep the Married column in the data set.